name: flutter_youtube
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  desktop_webview_auth: ^0.0.11
  google_sign_in: ^6.0.2
  loggy: ^2.0.3
  yt:
    path: ../../../yt
  # git: https://github.com/faithoflifedev/yt.git
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
